urls:
  - url: "/specs/openapi.AuthApi.yaml"
    name: "Auth API"
  - url: "/specs/openapi.MapApi.yaml"
    name: "Map API"
  - url: "/specs/openapi.SpotApi.yaml"
    name: "Spot API"
  - url: "/specs/openapi.ArticleApi.yaml"
    name: "Article API"
  - url: "/specs/openapi.ContentVersionApi.yaml"
    name: "Content version API"